package com.zodiacmc.ZodiacManager.Configurations;

public enum ConfigType {
	DEFAULT,
	RESTART,
	OLDPLAYTIME,
	RANK,
	CHOOSERANK,
	WORLDBLOCK,
	WORLDBLOCK_COMPUTER,
	WORLDBLOCK_TIMER,
	WORLDBLOCK_TELEPORT_TETHER,
	WORLDBLOCK_DIMENSIONAL_ANCHOR,
	WORLDBLOCK_HIGH_VOLTAGE_SOLAR_ARRAY,
	WORLDBLOCK_MEDIUM_VOLTAGE_SOLAR_ARRAY,
	WORLDBLOCK_LOW_VOLTAGE_SOLAR_ARRAY,
	WORLDBLOCK_WORLD_ANCHOR,
	MINIMUMPRICES,
	MALL
}
