name: ZodiacManager
authors: [TomCrawley_, reichman2]
version: 1.0
description: Plugin manager for Zodiac
main: com.zodiacmc.ZodiacManager.ZodiacManager
commands:
  automalls:
    description: Customized version of automall for ZodiacMC
    usage: /automalls
    aliases: [mall, malls]
  serverrestarter:
    description: Custom server restarter plugin for ZodiacMC
    usage: /serverrestarter
  autorank:
    description: Custom autorank plugin for ZodiacMC
    usage: /autorank
    aliases: [ar]
  minimumprices:
    description: Custom plugin for handling minimum prices for ZodiacMC
    usage: /minimumprices
    aliases: [minprice, minprices, checkprice]
  chunkmanager:
    description: Custom chunkmanager plugin for ZodiacMC
    usage: /chunkmanager
